openapi: 3.0.0
info:
  title: Real-Time Webcasting API
  description: API documentation for the Real-Time Webcasting application.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/events:
    post:
      summary: Create an event
      description: Creates a new event with a unique name. Requires authentication.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventName:
                  type: string
                  example: MyEvent123
      responses:
        '201':
          description: Event created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                    example: 64bde8e129...
                  eventName:
                    type: string
                    example: MyEvent123
        '400':
          description: Event name already exists.
  /api/auth/login:
    post:
      summary: Login
      description: Logged in into the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: adminpass
      responses:
        '201':
          description: Logged In successfully.
        '400':
          description: Invalid input.
